name: test
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'v2/**' # Only run on changes to the v2 directory
permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: stable
      - run: make test-cov
        working-directory: v2
